//
// Created by jsilva on 11-01-2018.
//

#ifndef CPP_SIMPLEBEGINNEREXAMPLES_REFERENCETYPES_H
#define CPP_SIMPLEBEGINNEREXAMPLES_REFERENCETYPES_H


class ReferenceTypes {

};


#endif //CPP_SIMPLEBEGINNEREXAMPLES_REFERENCETYPES_H
